name: gcoord_dart_null_safety
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/TonyStark106/gcoord_dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  test: any
  geo: any
#  extended_math: ^0.0.29+1
